version: v0.3.0

listeners:
  - type: model
    name: model_listener
    port: 12000

model_providers:
  # OpenAI Models
  - model: openai/gpt-5-2025-08-07
    access_key: $OPENAI_API_KEY
    routing_preferences:
      - name: code generation
        description: generating new code snippets, functions, or boilerplate based on user prompts or requirements

  - model: openai/gpt-4.1-2025-04-14
    access_key: $OPENAI_API_KEY
    routing_preferences:
      - name: code understanding
        description: understand and explain existing code snippets, functions, or libraries
  # Anthropic Models
  - model: anthropic/claude-sonnet-4-5
    default: true
    access_key: $ANTHROPIC_API_KEY

  - model: anthropic/claude-haiku-4-5
    access_key: $ANTHROPIC_API_KEY

  # Ollama Models
  - model: ollama/llama3.1
    base_url: http://host.docker.internal:11434


# Model aliases - friendly names that map to actual provider names
model_aliases:
  # Alias for a small faster Claude model
  arch.claude.code.small.fast:
    target: claude-haiku-4-5

tracing:
  random_sampling: 100
