agents:
- id: weather_agent
  url: http://host.docker.internal:10510
- id: flight_agent
  url: http://host.docker.internal:10520
endpoints:
  app_server:
    connect_timeout: 0.005s
    endpoint: 127.0.0.1
    port: 80
  flight_agent:
    endpoint: host.docker.internal
    port: 10520
    protocol: http
  input_guards:
    endpoint: host.docker.internal
    port: 10500
    protocol: http
  mistral_local:
    endpoint: 127.0.0.1
    port: 8001
  weather_agent:
    endpoint: host.docker.internal
    port: 10510
    protocol: http
filters:
- id: input_guards
  url: http://host.docker.internal:10500
listeners:
- address: 0.0.0.0
  agents:
  - description: virtual assistant for retrieval augmented generation tasks
    filter_chain:
    - input_guards
    id: rag_agent
  name: travel_booking_service
  port: 8001
  router: plano_orchestrator_v1
  type: agent
- address: 0.0.0.0
  name: model_1
  port: 12000
  type: model
- address: 0.0.0.0
  name: prompt_function_listener
  port: 10000
  type: prompt
- address: 0.0.0.0
  model_providers:
  - access_key: $OPENAI_API_KEY
    default: true
    model: gpt-4o
    name: openai/gpt-4o
    provider_interface: openai
  - access_key: $OPENAI_API_KEY
    model: gpt-4o-mini
    name: openai/gpt-4o-mini
    provider_interface: openai
  - access_key: $ANTHROPIC_API_KEY
    model: claude-sonnet-4-0
    name: anthropic/claude-sonnet-4-0
    provider_interface: anthropic
  - access_key: $MISTRAL_API_KEY
    model: ministral-3b-latest
    name: mistral/ministral-3b-latest
    provider_interface: mistral
  name: egress_traffic
  port: 12000
  timeout: 30s
  type: model_listener
model_aliases:
  fast-llm:
    target: gpt-4o-mini
  smart-llm:
    target: gpt-4o
model_providers:
- access_key: $OPENAI_API_KEY
  default: true
  model: gpt-4o
  name: openai/gpt-4o
  provider_interface: openai
- access_key: $OPENAI_API_KEY
  model: gpt-4o-mini
  name: openai/gpt-4o-mini
  provider_interface: openai
- access_key: $ANTHROPIC_API_KEY
  model: claude-sonnet-4-0
  name: anthropic/claude-sonnet-4-0
  provider_interface: anthropic
- access_key: $MISTRAL_API_KEY
  model: ministral-3b-latest
  name: mistral/ministral-3b-latest
  provider_interface: mistral
- model: Arch-Function
  name: arch-function
  provider_interface: arch
- model: Plano-Orchestrator
  name: plano-orchestrator
  provider_interface: arch
prompt_targets:
- description: Get current weather at a location.
  endpoint:
    http_method: POST
    name: app_server
    path: /weather
  name: get_current_weather
  parameters:
  - description: The location to get the weather for
    format: City, State
    name: location
    required: true
    type: string
  - description: the number of days for the request
    name: days
    required: true
    type: int
tracing:
  random_sampling: 100
version: v0.3.0
