services:
  rag-agents:
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "10500:10500"
      - "10501:10501"
      - "10502:10502"
      - "10505:10505"
    environment:
      - LLM_GATEWAY_ENDPOINT=${LLM_GATEWAY_ENDPOINT:-http://host.docker.internal:12000/v1}
      - OPENAI_API_KEY=${OPENAI_API_KEY:?OPENAI_API_KEY environment variable is required but not set}
  plano:
    build:
      context: ../../../
      dockerfile: Dockerfile
    ports:
      - "11000:11000"
      - "12001:12001"
      - "12000:12000"
      - "8001:8001"
    environment:
      - PLANO_CONFIG_PATH=/config/config.yaml
      - OPENAI_API_KEY=${OPENAI_API_KEY:?OPENAI_API_KEY environment variable is required but not set}
    volumes:
      - ./config.yaml:/app/plano_config.yaml
      - /etc/ssl/cert.pem:/etc/ssl/cert.pem
  jaeger:
    build:
      context: ../../shared/jaeger
    ports:
      - "16686:16686"
      - "4317:4317"
      - "4318:4318"
  anythingllm:
    image: mintplexlabs/anythingllm
    restart: always
    ports:
      - "3001:3001"
    cap_add:
      - SYS_ADMIN
    environment:
      - STORAGE_DIR=/app/server/storage
      - LLM_PROVIDER=generic-openai
      - GENERIC_OPEN_AI_BASE_PATH=http://plano:8001/v1
      - GENERIC_OPEN_AI_MODEL_PREF=gpt-4o-mini
      - GENERIC_OPEN_AI_MODEL_TOKEN_LIMIT=128000
      - GENERIC_OPEN_AI_API_KEY=sk-placeholder
